@include('home.header')

 
<div class="container">
    <div class="content-single-page content-page">
    <div class="page-hero-img">
    <img fetchpriority="high" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAS0AAAEsAQMAAACscXcIAAAABlBMVEUAAAD///+l2Z/dAAAAAXRSTlMAQObYZgAAAAlwSFlzAAAOxAAADsQBlSsOGwAAACJJREFUaN7twTEBAAAAwqD1T20KP6AAAAAAAAAAAAAAAHgZLbQAAf/pCWsAAAAASUVORK5CYII=" alt="Group (5)" width="301" height="300" data-src="https://PrimeCore Capitals.net/wp-content/uploads/2023/07/Group-5.svg" decoding="async" class="lazyload" data-eio-rwidth="301" data-eio-rheight="300" /><noscript><img fetchpriority="high"   src="../wp-content/uploads/2023/07/Group-5.svg"  alt="Group (5)" width="301" height="300" data-eio="l" /></noscript> </div>
    <h1 class="page-title">
    <span class="-c-accent">Terms</span> of Use </h1>
    <article id="post-28690368" class="post-28690368 page type-page status-publish hentry">
    <div class="is-wysiwyg">
    <p>Welcome to PrimeCore Capitals.net. The PrimeCore Capitals.net website (the Site) is comprised of various web pages operated by PrimeCore Capitals.net, LLC (PrimeCore Capitals). PrimeCore Capitals.net is offered to you conditioned on your acceptance without modification of the terms, conditions, and notices contained herein (the Terms). Your use of PrimeCore Capitals.net constitutes your agreement to all such Terms. Please read these terms carefully and keep a copy of them for your reference. These Terms are applicable for all services provided by PrimeCore Capitals Site shall mean all services and interactions made by PrimeCore Capitals.<br/>
    PrimeCore Capitals.net is an E-Commerce Site.<br/>
    The products and services offered on this Site are not in any way intended to be considered an investment. PrimeCore Capitals provides opportunities for Traders to receive funding by proving their skills in trading by passing evaluations with specific goals that must be achieved in order to pass the evaluations.<br/>
    Privacy</p>
    
    
     
   <h2> Notice Regarding Withdrawal Terms</h2>
 <p>Please be informed that a 15% brokerage fee is required upon submitting a withdrawal request for your total ROI (Return on Investment). This fee must be paid before the withdrawal process can be completed and your funds transferred to your designated bank account or crypto wallet.</p>

 <p>We kindly advise all clients to review and understand these terms prior to initiating a withdrawal request. For further assistance or clarification, please contact our support team.

Thank you for your cooperation.</p>
    <h2>Privacy</h2>
    <p>Your use of PrimeCore Capitals.net is subject to PrimeCore Capitalss Privacy Policy. Please review our Privacy Policy, which also governs the Site and informs users of our data collection practices.</p>
    <h2>Electronic Communications</h2>
    <p>Visiting PrimeCore Capitals.net or sending emails to PrimeCore Capitals constitutes electronic communications. You consent to receive electronic communications and you agree that all agreements, notices, disclosures and other communications that we provide to you electronically, via email and on the Site, satisfy any legal requirement that such communications be in writing.</p>
    <h2>Your Account</h2>
    <p>If you use this site, you are responsible for maintaining the confidentiality of your account and password and for restricting access to your computer, and you agree to accept responsibility for all activities that occur under your account or password. You may not assign or otherwise transfer your account to any other person or entity. You acknowledge that PrimeCore Capitals is not responsible for third-party access to your account that results from theft or misappropriation of your account. PrimeCore Capitals and its associates reserve the right to refuse or cancel service, terminate accounts, or remove or edit content at our sole discretion.</p>
    <p>For any evaluation programs that a client is provided through our website, under no circumstances is the client able to change the password to the demo trading account. Any changes to the password will result in a breach of these Terms of Use and will count their evaluation as failed.</p>
    <h2>Funded Account Terms</h2>
    <p>Evaluation accounts provided by PrimeCore Capitals are subject to 1:100 FOREX leverage, while funded accounts are subject to 1:100 FOREX leverage as is the industry standard for live accounts. All other instrument leverages are subject to the sole discretion of PrimeCore Capitals and what is deemed reasonable by PrimeCore Capitals to provide to clients based on risk management.</p>
    <h2>Children Under Eighteen</h2>
    <p>PrimeCore Capitals does not knowingly collect, either online or offline, personal information from persons under the age of Eighteen. If you are under 18, you may use PrimeCore Capitals.net only with the permission of a parent or guardian.</p>
    <h2>Links to Third Party Sites/Third Party Services</h2>
    <p>PrimeCore Capitals.net may contain links to other websites (Linked Sites). The Linked Sites are not under the control of PrimeCore Capitals and PrimeCore Capitals is not responsible for the contents of any Linked Site, including without limitation any link contained in a Linked Site, or any changes or updates to a Linked Site. PrimeCore Capitals is providing these links to you only as a convenience, and the inclusion of any link does not imply endorsement by PrimeCore Capitals of the site or any association with its operators.</p>
    <p>Certain services made available via PrimeCore Capitals.net are delivered by third-party sites and organizations. By using any product, service or functionality originating from the PrimeCore Capitals.net domain, you hereby acknowledge and consent that PrimeCore Capitals may share such information and data with any third party with whom PrimeCore Capitals has a contractual relationship to provide the requested product, service, or functionality on behalf of PrimeCore Capitals.net users and customers.</p>
    <h2>No Unlawful or Prohibited Use/Intellectual Property</h2>
    <p>You are granted a non-exclusive, non-transferable, revocable license to access and use PrimeCore Capitals.net strictly in accordance with these terms of use. As a condition of your use of the Site, you warrant to PrimeCore Capitals that you will not use the Site for any purpose that is unlawful or prohibited by these Terms. You may not use the Site in any manner which could damage, disable, overburden, or impair the Site or interfere with any other parties’ use and enjoyment of the Site. You may not obtain or attempt to obtain any materials or information through any means not intentionally made available or provided for through the Site.</p>
    <p>All content included as part of the Service, such as text, graphics, logos, images, as well as the compilation thereof, and any software used on the Site, is the property of PrimeCore Capitals or its suppliers and protected by copyright and other laws that protect intellectual property and proprietary rights. You agree to observe and abide by all copyright and other proprietary notices, legends, or other restrictions contained in any such content and will not make any changes thereto.</p>
    <p>You will not modify, publish, transmit, reverse engineer, participate in the transfer or sale, create derivative works, or in any way exploit any of the content, in whole or in part, found on the Site. PrimeCore Capitals content is not for resale. Your use of the Site does not entitle you to make any unauthorized use of any protected content, and in particular, you will not delete or alter any proprietary rights or attribution notices in any content. You will use protected content solely for your personal use and will make no other use of the content without the express written permission of PrimeCore Capitals and the copyright owner. You agree that you do not acquire any ownership rights in any protected content. We do not grant you any licenses, express or implied, to the intellectual property of PrimeCore Capitals or our licensors except as expressly authorized by these Terms.</p>
    <h2>International Users</h2>
    <p>The Service is controlled, operated, and administered by PrimeCore Capitals from our offices within the USA. If you access the Service from a location outside the USA, you are responsible for compliance with all local laws. You agree that you will not use PrimeCore Capitals Content accessed through PrimeCore Capitals.net in any country or in any manner prohibited by any applicable laws, restrictions, or regulations.</p>
    <h2>Legal and Market Compliance</h2>
    <p>PrimeCore Capitals takes compliance with relevant statutes, regulations, and judgments seriously and asks our customers to do the same. Further, PrimeCore Capitals also respects the functioning of the real market. As such, predatory trading practices that interfere with the functioning of the real market are banned on our platform. Predatory trading practices that do not comply with the functioning of the real market include, but not limited to:</p>
    <ol>
    <li>Use of platform or data freezing</li>
    <li>Use of delayed data feed</li>
    <li>Trading on delayed charts</li>
    <li>Trading at a time of significant macroeconomic reports</li>
    <li>Use of the guarantee of compliance with limited orders</li>
    <li>Use of hedging trades between accounts</li>
    </ol>
    <p>For further guidance on predatory trading practices that do not comply with the functioning of the real market, visit the link: <a href="https://help.PrimeCore Capitals.net/en/articles/5374175-trading-according-tothe-real-market">https://help.PrimeCore Capitals.net/en/articles/5374175-trading-according-tothe-real-market</a>.</p>
    <p>Breach of these Terms or laws in any way may lead to immediate termination of all accounts<br/>
    associated with our services, and no refund or payment of any kind shall be issued. In addition,<br/>
    you may be held civilly and/or criminally liable if you are in breach of these Terms and relevant laws.</p>
    <h2>Indemnification</h2>
    <p>You agree to indemnify, defend and hold harmless PrimeCore Capitals, its officers, directors, employees, agents and third parties, for any losses, costs, liabilities, and expenses (including reasonable attorneys fees) relating to or arising out of your use of or inability to use the Site or services, any user postings made by you, your violation of any terms of this Agreement or your violation of any rights of a third party, or your violation of any applicable laws, rules or regulations. PrimeCore Capitals reserves the right, at its own cost, to assume the exclusive defense and control of any matter otherwise subject to indemnification by you, in which event you will fully cooperate with PrimeCore Capitals in asserting any available defenses.</p>
    <h2>Arbitration</h2>
    <p>In the event, the parties are not able to resolve any dispute between them arising out of or concerning these Terms or any provisions hereof, whether in contract, tort, or otherwise at law or in equity for damages or any other relief, then such dispute shall be resolved only by final and binding arbitration pursuant to the Federal Arbitration Act, conducted by a single neutral arbitrator and administered by the American Arbitration Association, or a similar arbitration service selected by the parties, in a location mutually agreed upon by the parties.</p>
    <p>The arbitrators award shall be final, and judgment may be entered upon it in any court having jurisdiction. In the event that any legal or equitable action, proceeding, or arbitration arises out of or concerns these Terms and Conditions, the prevailing party shall be entitled to recover its costs and reasonable attorney fees. The parties agree to arbitrate all disputes and claims with regards to these Terms or any disputes arising as a result of these Terms, whether directly or indirectly, including Tort claims that are a result of these Terms. The parties agree that the Federal Arbitration Act governs the interpretation and enforcement of this provision. The entire dispute, including the scope and enforceability of this arbitration provision, shall be determined by the arbitrator. This arbitration provision shall survive the termination of these Terms. Consistent with other provisions stated elsewhere, the laws of the State of Texas shall apply to the arbitration proceedings.</p>
    <p>Any physical complaints notices and requests for arbitration can be sent to:</p>
    <p>PrimeCore Capitals.net, LLC</p>
    <p>547 NW 28th St</p>
    <p>Miami, FL 33127</p>
    <p>If able, please provide an electronic copy of the complaint or notice to the following email address:</p>
    <p><a href="../cdn-cgi/l/email-protection.html#aad9dfdadac5d8deeadec5dadec3cfd8ded8cbcecfd884c9c5c7"><span class="__cf_email__" data-cfemail="1b686e6b6b74696f5b6f746b6f727e696f697a7f7e6935787476">[email&#160;protected]</span></a></p>
    <h2>Class Action Waiver</h2>
    <p>Any arbitration under these Terms and Conditions will take place on an individual basis; class arbitrations and class/representative/collective actions are not permitted. THE PARTIES AGREE THAT A PARTY MAY BRING CLAIMS AGAINST THE OTHER ONLY IN EACH INDIVIDUAL CAPACITY, AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PUTATIVE CLASS, COLLECTIVE, AND/ OR REPRESENTATIVE PROCEEDING, SUCH AS IN THE FORM OF A PRIVATE ATTORNEY GENERAL ACTION AGAINST THE OTHER. Further, unless both you and PrimeCore Capitals agree otherwise, the arbitrator may not consolidate more than one person’s claims and may not otherwise preside over any form of a representative or class proceeding.</p>
    <h2>Disclaimers</h2>
    <p>THE INFORMATION, SOFTWARE, PRODUCTS, AND SERVICES INCLUDED IN OR AVAILABLE THROUGH THE SITE MAY INCLUDE INACCURACIES OR TYPOGRAPHICAL ERRORS. CHANGES ARE PERIODICALLY ADDED TO THE INFORMATION HEREIN. PrimeCore Capitals.net, LLC AND/OR ITS SUPPLIERS MAY MAKE IMPROVEMENTS AND/OR CHANGES TO THE SITE AT ANY TIME.</p>
    <p>PrimeCore Capitals.net, LLC AND/OR ITS SUPPLIERS MAKE NO REPRESENTATIONS ABOUT THE SUITABILITY, RELIABILITY, AVAILABILITY, TIMELINESS, AND ACCURACY OF THE INFORMATION, SOFTWARE, PRODUCTS, SERVICES, AND RELATED GRAPHICS CONTAINED ON THE SITE FOR ANY PURPOSE. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, ALL SUCH INFORMATION, SOFTWARE, PRODUCTS, SERVICES, AND RELATED GRAPHICS ARE PROVIDED  WITHOUT WARRANTY OR CONDITION OF ANY KIND. PrimeCore Capitals.net, LLC AND/OR ITS SUPPLIERS HEREBY DISCLAIM ALL WARRANTIES AND CONDITIONS WITH REGARD TO THIS INFORMATION, SOFTWARE, PRODUCTS, SERVICES, AND RELATED GRAPHICS, INCLUDING ALL IMPLIED WARRANTIES OR CONDITIONS OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT.</p>
    <p>TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL PrimeCore Capitals.net, LLC AND/OR ITS SUPPLIERS BE LIABLE FOR ANY DIRECT, INDIRECT, PUNITIVE, INCIDENTAL, SPECIAL, CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OF USE, DATA OR PROFITS, ARISING OUT OF OR IN ANY WAY CONNECTED WITH THE USE OR PERFORMANCE OF THE SITE, WITH THE DELAY OR INABILITY TO USE THE SITE OR RELATED SERVICES, THE PROVISION OF OR FAILURE TO PROVIDE SERVICES, OR FOR ANY INFORMATION, SOFTWARE, PRODUCTS, SERVICES AND RELATED GRAPHICS OBTAINED THROUGH THE SITE, OR OTHERWISE ARISING OUT OF THE USE OF THE SITE, WHETHER BASED ON CONTRACT, TORT, NEGLIGENCE, STRICT LIABILITY OR OTHERWISE, EVEN IF PrimeCore Capitals.net, LLC OR ANY OF ITS SUPPLIERS HAS BEEN ADVISED OF THE POSSIBILITY OF DAMAGES. BECAUSE SOME STATES/JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF LIABILITY FOR CONSEQUENTIAL OR INCIDENTAL DAMAGES, THE ABOVE LIMITATION MAY NOT APPLY TO YOU. IF YOU ARE DISSATISFIED WITH ANY PORTION OF THE SITE, OR WITH ANY OF THESE TERMS OF USE, YOUR SOLE AND EXCLUSIVE REMEDY IS TO DISCONTINUE USING THE SITE.</p>
    <p>Hypothetical or simulated performance results have certain limitations. Unlike an actual performance record, simulated results do not represent actual trading. Also, because the trades have not actually been executed, the results may have under-or-over compensated for the impact, if any, of certain market factors, such as lack of liquidity. Simulated trading programs, in general, are also subject to the fact that they are designed with the benefit of hindsight. No representation is being made that any account will or is likely to achieve profit or losses similar to those shown.</p>
    <h2>Termination/Access Restriction</h2>
    <p>PrimeCore Capitals reserves the right, in its sole discretion, to terminate your access to the Site and the related services or any portion thereof at any time, without notice. To the maximum extent permitted by law, these Terms are governed by the laws of the State of Delaware and you hereby consent to the exclusive jurisdiction and venue of the courts in Miami-Dade County, New Jersey, in all disputes arising out of or relating to the use of the Site, should arbitration efforts fail. Use of the Site is unauthorized in any jurisdiction that does not give effect to all provisions of these Terms, including, without limitation, this section.</p>
    <p>You agree that no joint venture, partnership, employment, or agency relationship exists between you and PrimeCore Capitals as a result of this agreement or use of the Site. PrimeCore Capitals’s performance of this agreement is subject to existing laws and legal processes, and nothing contained in this agreement is in derogation of PrimeCore Capitals’s right to comply with governmental, court, and law enforcement requests or requirements relating to your use of the Site or information provided to or gathered by PrimeCore Capitals with respect to such use. If any part of this agreement is determined to be invalid or unenforceable pursuant to applicable law including, but not limited to, the warranty disclaimers and liability limitations set forth above, then the invalid or unenforceable provision will be deemed superseded by a valid, enforceable provision or statement that most closely matches the intent of the original provision and the remainder of the agreement shall continue in effect.</p>
    <p>Unless otherwise specified herein, this agreement constitutes the entire agreement between the user and PrimeCore Capitals with respect to the Site and it supersedes all prior or contemporaneous communications and proposals, whether electronic, oral or written, between the user and PrimeCore Capitals with respect to the Site. A printed version of this agreement and of any notice given in electronic form shall be admissible in judicial or administrative proceedings based upon or relating to this agreement to the same extent and subject to the same conditions as other business documents and records originally generated and maintained in printed form. It is the express wish of the parties that this agreement and all related documents be written in English.</p>
    <h2>Changes to Terms</h2>
    <p>PrimeCore Capitals reserves the right, in its sole discretion, to change the Terms under which PrimeCore Capitals.net is offered. The most current version of the Terms will supersede all previous versions. PrimeCore Capitals encourages you to periodically review the Terms to stay informed of our updates.</p>
    <p>These Terms are effective as ofÂ <strong>September 28, 2021</strong></p>
    </div>
    </article>
    </div>
    </div>
    </main>
        <!-- section content end -->
@include('home.footer')